---
- name: "Activiti MySQL DB Deployment with Ansible Playbook (EC2 hosting)"
  hosts: localhost
  connection: local
  become: False
  vars:
    security_group: sg-029126963d349ab49
  tasks:
  - name: Restore Activiti App MySQL-DB from EC2 AMI 
    local_action:
      module: ec2_instance
      key_name: 'mysql_db_kp'
      instance_type: t3.micro
      image_id: ami-04fa64dacd13c95a9
      security_group: '{{ security_group }}'
      secret_key: '{{ secret_key }}'
      access_key: '{{ access_key }}'
      region: us-east-1
      wait: yes
      wait_timeout: 1200
      tags:
          Name: Ansible_MySQL-DB_EC2
    register: newinstance

  - name: Associate EIP with MySQL - EC2 instance
    local_action:
      module: ec2_eip
      device_id: "{{ newinstance.instance_ids[0] }}"
      region: us-east-1
      in_vpc: true
      reuse_existing_ip_allowed: true
      state: present
      public_ip: 34.203.95.105

